import { Marque } from '../classes/marque.classe';

export const marques: Marque[] = [

  {id:'1',
  marque:"alfa romeo",
  photo:"https://catalogue.automobile.tn/marques/1.png"
  },

  {id:'2',
  marque:"audi",
  photo:"https://catalogue.automobile.tn/marques/2.png"
  },

  {id:'3',
  marque:"bmw",
  photo:"https://catalogue.automobile.tn/marques/3.png"
  },

  {id:'4',
  marque:"Chery",
  photo:"https://catalogue.automobile.tn/marques/1544.png"
  },
  {id:'5',
  marque:"ciroen",
  photo:"https://catalogue.automobile.tn/marques/5.png"
  },
  {id:'6',
  marque:"dacia",
  photo:"https://catalogue.automobile.tn/marques/64.png"
  },
  {id:'7',
  marque:"dfsk",
  photo:"https://catalogue.automobile.tn/marques/1602.png"
  },
  {id:'8',
  marque:"Dongfeng",
  photo:"https://catalogue.automobile.tn/marques/1640.png"
  },
  {id:'9',
  marque:"ds",
  photo:"https://catalogue.automobile.tn/marques/1523.png"
  },
  {id:'10',
  marque:"fiat",
  photo:"https://catalogue.automobile.tn/marques/88.png"
  },
  {id:'11',
  marque:"ford",
  photo:"https://catalogue.automobile.tn/marques/6.png"
  },

  {id:'12',
  marque:"foton",
  photo:"https://catalogue.automobile.tn/marques/1644.png"
  },

  {id:'13',
  marque:"Geely",
  photo:"https://catalogue.automobile.tn/marques/1615.png"
  },
  {id:'14',
  marque:"Great Wall",
  photo:"https://catalogue.automobile.tn/marques/1549.png"
  },

  {id:'15',
  marque:"Haval",
  photo:"https://catalogue.automobile.tn/marques/1550.png"
  },
  {id:'16',
  marque:"Honda",
  photo:"https://catalogue.automobile.tn/marques/188.png"
  },
  {id:'17',
  marque:"Hyundai",
  photo:"https://catalogue.automobile.tn/marques/216.png"
  },
  {id:'18',
  marque:"Jaguar",
  photo:"https://catalogue.automobile.tn/marques/144.png"
  },
  {id:'19',
  marque:"Jeep",
  photo:"https://catalogue.automobile.tn/marques/690.png"
  },
  {id:'20',
  marque:"kia",
  photo:"https://catalogue.automobile.tn/marques/7.png"
  },
  {id:'21',
  marque:"lada",
  photo:"https://catalogue.automobile.tn/marques/727.png"
  },
  {id:'22',
  marque:"Land Rover",
  photo:"https://catalogue.automobile.tn/marques/137.png"
  },
  {id:'23',
  marque:"Mahindra",
  photo:"https://catalogue.automobile.tn/marques/1497.png"
  },
  {id:'24',
  marque:"Mazda",
  photo:"https://catalogue.automobile.tn/marques/8.png"
  },
  {id:'25',
  marque:"Mercedes",
  photo:"https://catalogue.automobile.tn/marques/9.png"
  },
  {id:'26',
  marque:"mg",
  photo:"https://catalogue.automobile.tn/marques/904.png"
  },
  {id:'27',
  marque:"mini",
  photo:"https://catalogue.automobile.tn/marques/198.png"
  },
  {id:'28',
  marque:"Mitsubishi",
  photo:"https://catalogue.automobile.tn/marques/1504.png"
  },
  {id:'29',
  marque:"nissan",
  photo:"https://catalogue.automobile.tn/marques/10.png"
  },
  {id:'30',
  marque:"Peugeot",
  photo:"https://catalogue.automobile.tn/marques/12.png"
  },
  {id:'31',
  marque:"porsche",
  photo:"https://catalogue.automobile.tn/marques/125.png"
  },
  {id:'32',
  marque:"renault",
  photo:"https://catalogue.automobile.tn/marques/13.png"
  },
  {id:'33',
  marque:"seat",
  photo:"https://catalogue.automobile.tn/marques/14.png"
  },
  {id:'34',
  marque:"skoda",
  photo:"https://catalogue.automobile.tn/marques/1209.png"
  },
  {id:'35',
  marque:"ssangyong",
  photo:"https://catalogue.automobile.tn/marques/221.png"
  },
  {id:'36',
  marque:"suzuki",
  photo:"https://catalogue.automobile.tn/marques/1246.png"
  },
  {id:'37',
  marque:"tata",
  photo:"https://catalogue.automobile.tn/marques/1268.png"
  },
  {id:'38',
  marque:"toyota",
  photo:"https://catalogue.automobile.tn/marques/207.png"
  },
  {id:'39',
  marque:"volkswagen",
  photo:"https://catalogue.automobile.tn/marques/15.png"
  },
  {id:'40',
  marque:"wallyscar",
  photo:"https://catalogue.automobile.tn/marques/1467.png"
  },
  {id:'41',
  marque:"chevrolet",
  photo:"https://catalogue.automobile.tn/marques/4.png"
  },

]
